jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies in the frontend directory
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend  # Ensure this path is correct

      # Run unit tests
      - name: Run Unit Tests
        run: npm test
        working-directory: ./frontend  # Ensure this path is correct

      # Run Postman API Tests
      - name: Run Postman API Tests
        run: newman run ./tests/postman-collection.json
        working-directory: ./frontend  # Ensure this path is correct

      # Run UI Automation Tests
      - name: Run UI Automation Tests
        run: node ./tests/selenium-tests.js
        working-directory: ./frontend  # Ensure this path is correct

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Optional: Deploy your application
      - name: Deploy Application
        run: |
          echo "Deploying your application to production..."  # Customize deployment script
