name: CI (Build & All Tests)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Backend: unit + API + BDD ----------
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: maven-

      - name: Build backend & run all JUnit (unit, REST Assured, Cucumber)
        working-directory: backend
        run: mvn -B -U verify   # runs tests

      - name: Package backend
        working-directory: backend
        run: mvn -B -DskipTests package

      # ---------- Frontend: build ----------
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # ---------- Start apps for UI E2E ----------
      - name: Start backend JAR
        run: |
          nohup java -jar backend/target/*.jar > server.log 2>&1 &
          for i in {1..30}; do
            curl -sf http://localhost:8080/tasks && break || sleep 2
          done

      - name: Serve built frontend (dist)
        working-directory: frontend
        run: nohup npx http-server ./dist -p 5173 -s > ui.log 2>&1 &

      # ---------- Selenium UI tests ----------
    #   - name: Install Chrome
    #     uses: browser-actions/setup-chrome@v1

    #   - name: Run Selenium E2E
    #     working-directory: frontend
    #     env:
    #       CHROME_PATH: 
    #     run: npm run selenium:e2e

      # ---------- Artifacts (optional) ----------
      - name: Upload backend jar
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar

      - name: Upload frontend dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
